version: "3.9"

networks:
  ipacx_core:
    driver: bridge
  ipacx_db:
    driver: bridge

volumes:
  ipacx_pgdata:
  ipacx_portainer:

services:

  postgres:
    image: postgres:15
    container_name: ipacx-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ipacx_pgdata:/var/lib/postgresql/data
    networks:
      - ipacx_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
services:
  backend:
    build: ./backend
    container_name: ipacx-backend
    env_file:
      - .env
    depends_on:
      - postgres


  portainer:
    image: portainer/portainer-ce:latest
    container_name: ipacx-portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ipacx_portainer:/data
    networks:
      - ipacx_core
