version: "3.9"

services:
  ohif:
    image: ohif/viewer:latest
    container_name: ipacx-ohif
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./app-config.js:/usr/share/nginx/html/app-config.js:ro
