services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: ipacx-orthanc
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
    environment:
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      ORTHANC__REGISTERED_USERS__ipacx-admin: "ipacx123"
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./config:/etc/orthanc:ro
    networks:
      - ipacx_pacs

volumes:
  orthanc_data:

networks:
  ipacx_pacs:
    external: true
